name: Tests

on:
  - push

jobs:
  test:
    strategy:
      matrix:
        py:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy3.7"
          - "pypy3.8"
          - "pypy3.9"
        pyramid_version:
          - "<2"
          - ">=2"

    name: "Python: ${{ matrix.py }}, Pyramid: ${{ matrix.pyramid_version }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install
        run: pip install .[testing] "pyramid${{ matrix.pyramid_version }}"
      - name: Running tests
        run: pytest tests

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install
        run: pip install .[linting]
      - name: Flake8
        run: flake8 pyramid_resource.py tests examples
      - name: Black
        run: black --check pyramid_resource.py tests examples
      - name: isort
        run: isort --check pyramid_resource.py tests examples
